services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5450:5432"
    volumes:
      - db-data:/var/lib/postgresql/data



volumes:
  db-data: